project_id = "nghkrmvakjomzmfwdhbo"

[functions.generate-monthly-charges]
verify_jwt = false

[functions.process-invoice-reminders]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.admin-bootstrap]
verify_jwt = false