project_id = "nghkrmvakjomzmfwdhbo"

[functions.generate-monthly-charges]
verify_jwt = false

[functions.process-invoice-reminders]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.import-ski-monitors]
verify_jwt = false