-- Point 7 : seed des 445 phrases de test_phrases_complete.json.
-- La métadonnée du fichier annonce 540 phrases ; le tableau "phrases" en contient 445.
-- On importe ce qui existe, sans dédoublonner ni renommer les étiquettes.
-- Copie de référence du fichier (encodage corrigé) : src/data/test_phrases_complete.json
-- Reprise possible à volonté : ON CONFLICT (code) met à jour le contenu du fichier
-- et laisse profession / level_min / level_max / active à la main de l'administration.

INSERT INTO public.test_phrases
  (code, language, category, text_fr, context, is_correction, error_type, is_positive, order_index, active)
VALUES
  ('INTRO-01', 'COMMON', 'INTRODUCTION', 'Bonjour, je suis [Nom]. Je serai votre examinateur aujourd''hui.', 'Accueil candidat', false, NULL, true, 1, true),
  ('INTRO-02', 'COMMON', 'INTRODUCTION', 'Bienvenue à ce test de langue pour moniteurs de ski.', 'Accueil candidat', false, NULL, true, 2, true),
  ('INTRO-03', 'COMMON', 'INTRODUCTION', 'Ce test évalue votre capacité à communiquer dans un contexte d''enseignement du ski.', 'Explication test', false, NULL, true, 3, true),
  ('INTRO-04', 'COMMON', 'INTRODUCTION', 'Le test dure environ 30 minutes.', 'Durée', false, NULL, true, 4, true),
  ('INTRO-05', 'COMMON', 'INTRODUCTION', 'Nous allons évaluer votre prononciation, votre grammaire et votre vocabulaire technique.', 'Critères', false, NULL, true, 5, true),
  ('INTRO-06', 'COMMON', 'INTRODUCTION', 'N''hésitez pas à me demander de répéter si vous ne comprenez pas.', 'Consigne', false, NULL, true, 6, true),
  ('INTRO-07', 'COMMON', 'INTRODUCTION', 'Essayez de répondre le plus naturellement possible.', 'Consigne', false, NULL, true, 7, true),
  ('INTRO-08', 'COMMON', 'INTRODUCTION', 'Êtes-vous prêt(e) à commencer ?', 'Démarrage', false, NULL, true, 8, true),
  ('INTRO-09', 'COMMON', 'INTRODUCTION', 'Commençons par quelques questions générales.', 'Transition', false, NULL, true, 9, true),
  ('INTRO-10', 'COMMON', 'INTRODUCTION', 'Parlez-moi de votre expérience en tant que skieur.', 'Question ouverte', false, NULL, true, 10, true),
  ('INTRO-11', 'COMMON', 'INTRODUCTION', 'Depuis combien de temps enseignez-vous le ski ?', 'Question expérience', false, NULL, true, 11, true),
  ('INTRO-12', 'COMMON', 'INTRODUCTION', 'Pourquoi avez-vous choisi de devenir moniteur de ski ?', 'Question motivation', false, NULL, true, 12, true),
  ('INTRO-13', 'COMMON', 'INTRODUCTION', 'Où avez-vous appris cette langue ?', 'Question parcours', false, NULL, true, 13, true),
  ('INTRO-14', 'COMMON', 'INTRODUCTION', 'Avez-vous déjà enseigné à des élèves parlant cette langue ?', 'Question expérience', false, NULL, true, 14, true),
  ('INTRO-15', 'COMMON', 'INTRODUCTION', 'Dans quelle station travaillez-vous habituellement ?', 'Question contexte', false, NULL, true, 15, true),
  ('COMP-01', 'COMMON', 'COMPREHENSION', 'Pouvez-vous répéter, s''il vous plaît ?', 'Demande répétition', false, NULL, true, 16, true),
  ('COMP-02', 'COMMON', 'COMPREHENSION', 'Je vais répéter plus lentement.', 'Répétition lente', false, NULL, true, 17, true),
  ('COMP-03', 'COMMON', 'COMPREHENSION', 'Est-ce que vous comprenez la question ?', 'Vérification', false, NULL, true, 18, true),
  ('COMP-04', 'COMMON', 'COMPREHENSION', 'Je vais reformuler autrement.', 'Reformulation', false, NULL, true, 19, true),
  ('COMP-05', 'COMMON', 'COMPREHENSION', 'Prenez votre temps pour répondre.', 'Encouragement', false, NULL, true, 20, true),
  ('COMP-06', 'COMMON', 'COMPREHENSION', 'N''hésitez pas à demander des clarifications.', 'Encouragement', false, NULL, true, 21, true),
  ('COMP-07', 'COMMON', 'COMPREHENSION', 'Avez-vous besoin que je répète ?', 'Vérification', false, NULL, true, 22, true),
  ('COMP-08', 'COMMON', 'COMPREHENSION', 'Très bien, continuons.', 'Transition', false, NULL, true, 23, true),
  ('COMP-09', 'COMMON', 'COMPREHENSION', 'Passons à la partie suivante.', 'Transition', false, NULL, true, 24, true),
  ('COMP-10', 'COMMON', 'COMPREHENSION', 'Nous allons maintenant passer aux jeux de rôle.', 'Transition', false, NULL, true, 25, true),
  ('COMP-11', 'COMMON', 'COMPREHENSION', 'Imaginez que je suis votre élève.', 'Mise en situation', false, NULL, true, 26, true),
  ('COMP-12', 'COMMON', 'COMPREHENSION', 'Je vais jouer le rôle d''un débutant.', 'Mise en situation', false, NULL, true, 27, true),
  ('COMP-13', 'COMMON', 'COMPREHENSION', 'Comment expliqueriez-vous cela à un enfant ?', 'Mise en situation', false, NULL, true, 28, true),
  ('COMP-14', 'COMMON', 'COMPREHENSION', 'Décrivez-moi comment faire un virage.', 'Question technique', false, NULL, true, 29, true),
  ('COMP-15', 'COMMON', 'COMPREHENSION', 'Que dites-vous à un élève qui a peur ?', 'Question pédagogique', false, NULL, true, 30, true),
  ('COMP-16', 'COMMON', 'COMPREHENSION', 'Comment gérez-vous une situation d''urgence ?', 'Question sécurité', false, NULL, true, 31, true),
  ('COMP-17', 'COMMON', 'COMPREHENSION', 'Excellente réponse.', 'Feedback positif', false, NULL, true, 32, true),
  ('COMP-18', 'COMMON', 'COMPREHENSION', 'C''est correct.', 'Feedback positif', false, NULL, true, 33, true),
  ('COMP-19', 'COMMON', 'COMPREHENSION', 'Pas tout à fait, essayez encore.', 'Feedback correctif', false, NULL, true, 34, true),
  ('COMP-20', 'COMMON', 'COMPREHENSION', 'Pouvez-vous développer cette réponse ?', 'Demande précision', false, NULL, true, 35, true),
  ('CONCL-01', 'COMMON', 'CONCLUSION', 'Nous arrivons à la fin du test.', 'Conclusion', false, NULL, true, 36, true),
  ('CONCL-02', 'COMMON', 'CONCLUSION', 'Merci pour votre participation.', 'Remerciement', false, NULL, true, 37, true),
  ('CONCL-03', 'COMMON', 'CONCLUSION', 'Avez-vous des questions sur le test ?', 'Questions', false, NULL, true, 38, true),
  ('CONCL-04', 'COMMON', 'CONCLUSION', 'Les résultats seront communiqués dans les prochains jours.', 'Information résultats', false, NULL, true, 39, true),
  ('CONCL-05', 'COMMON', 'CONCLUSION', 'Vous recevrez un rapport détaillé par email.', 'Information résultats', false, NULL, true, 40, true),
  ('CONCL-06', 'COMMON', 'CONCLUSION', 'Bonne continuation dans votre apprentissage.', 'Encouragement', false, NULL, true, 41, true),
  ('CONCL-07', 'COMMON', 'CONCLUSION', 'N''hésitez pas à continuer à pratiquer.', 'Conseil', false, NULL, true, 42, true),
  ('CONCL-08', 'COMMON', 'CONCLUSION', 'Je vous souhaite une bonne saison.', 'Salutation', false, NULL, true, 43, true),
  ('CONCL-09', 'COMMON', 'CONCLUSION', 'Au revoir et à bientôt.', 'Salutation', false, NULL, true, 44, true),
  ('CONCL-10', 'COMMON', 'CONCLUSION', 'Félicitations pour avoir complété ce test.', 'Félicitations', false, NULL, true, 45, true),
  ('EXPR-PT-01', 'PT', 'PRONONCIATION', 'Attention à la prononciation des voyelles nasales portugaises (ão, ãe, õe) qui sont différentes du français.', NULL, false, 'Nasais', true, 46, true),
  ('EXPR-PT-02', 'PT', 'PRONONCIATION', 'Le "R" initial ou double en portugais brésilien se prononce comme un "H" aspiré : "Rio" = "Hio".', NULL, false, 'R inicial', true, 47, true),
  ('EXPR-PT-03', 'PT', 'PRONONCIATION', 'Votre "R" français est trop marqué : en brésilien, le "R" en début de mot ou double est aspiré.', NULL, true, 'R français', false, 48, true),
  ('EXPR-PT-04', 'PT', 'PRONONCIATION', 'Le "S" en fin de syllabe se prononce souvent "CH" au Brésil : "mesmo" → "mechmo".', NULL, false, 'S final', true, 49, true),
  ('EXPR-PT-05', 'PT', 'PRONONCIATION', 'Attention au "LH" qui se prononce comme le "LL" espagnol ou le "GLI" italien, pas comme un L+H.', NULL, false, 'LH', true, 50, true),
  ('EXPR-PT-06', 'PT', 'PRONONCIATION', 'Le "NH" se prononce comme le "GN" français (montagne) : "montanha" = "montagna".', NULL, false, 'NH', true, 51, true),
  ('EXPR-PT-07', 'PT', 'PRONONCIATION', 'Le "D" devant "I" ou "E" se prononce souvent "DJ" au Brésil : "dia" → "djia".', NULL, false, 'D + i/e', true, 52, true),
  ('EXPR-PT-08', 'PT', 'PRONONCIATION', 'Le "T" devant "I" ou "E" se prononce souvent "TCH" au Brésil : "time" → "tchime".', NULL, false, 'T + i/e', true, 53, true),
  ('EXPR-PT-09', 'PT', 'PRONONCIATION', 'Votre accent français est très perceptible et peut gêner la compréhension.', NULL, true, 'Accent général', false, 54, true),
  ('EXPR-PT-10', 'PT', 'PRONONCIATION', 'Attention à l''accent tonique qui est essentiel en portugais : "médico" vs "medico".', NULL, false, 'Accent tonique', true, 55, true),
  ('GRAM-PT-01', 'PT', 'GRAMMAIRE', 'En portugais, le sujet est souvent omis car la conjugaison suffit : "Eu falo" → "Falo".', NULL, false, 'Sujet omis', true, 56, true),
  ('GRAM-PT-02', 'PT', 'GRAMMAIRE', 'Attention à SER (permanent) vs ESTAR (temporaire) : "Sou professor" vs "Estou cansado".', NULL, false, 'Ser/Estar', true, 57, true),
  ('GRAM-PT-03', 'PT', 'GRAMMAIRE', 'Vous confondez SER et ESTAR : c''est un point fondamental à maîtriser.', NULL, true, 'Ser/Estar', false, 58, true),
  ('GRAM-PT-04', 'PT', 'GRAMMAIRE', 'Le gérondif (-NDO) s''utilise beaucoup au Brésil : "Estou esquiando" (je suis en train de skier).', NULL, false, 'Gérondif', true, 59, true),
  ('GRAM-PT-05', 'PT', 'GRAMMAIRE', 'Le pluriel des mots en -ÃO peut être -ÕES, -ÃES ou -ÃOS : apprenez-les au cas par cas.', NULL, false, 'Pluriel -ão', true, 60, true),
  ('GRAM-PT-06', 'PT', 'GRAMMAIRE', 'La préposition "EM" se contracte avec les articles : em + o = no, em + a = na.', NULL, false, 'Contractions', true, 61, true),
  ('GRAM-PT-07', 'PT', 'GRAMMAIRE', 'Attention aux prépositions : "pensar EM" (penser à), "gostar DE" (aimer), "precisar DE" (avoir besoin de).', NULL, false, 'Prépositions', true, 62, true),
  ('GRAM-PT-08', 'PT', 'GRAMMAIRE', 'Vous traduisez littéralement les prépositions du français : elles sont différentes en portugais.', NULL, true, 'Prépositions', false, 63, true),
  ('GRAM-PT-09', 'PT', 'GRAMMAIRE', 'Le subjonctif (subjuntivo) est très utilisé en portugais, plus qu''en français moderne.', NULL, false, 'Subjonctif', true, 64, true),
  ('GRAM-PT-10', 'PT', 'GRAMMAIRE', '"Haver" impersonnel : "Há muita neve" (il y a beaucoup de neige), pas "Tem muita neve" (familier).', NULL, false, 'Haver/Ter', true, 65, true),
  ('GRAM-PT-11', 'PT', 'GRAMMAIRE', 'Attention au placement des pronoms : en brésilien parlé, ils vont souvent avant le verbe.', NULL, false, 'Pronoms', true, 66, true),
  ('GRAM-PT-12', 'PT', 'GRAMMAIRE', 'Le placement des pronoms est souvent incorrect dans vos phrases.', NULL, true, 'Pronoms', false, 67, true),
  ('GRAM-PT-13', 'PT', 'GRAMMAIRE', 'Les possessifs s''accordent avec l''objet possédé : "meu ski" / "minha prancha".', NULL, false, 'Possessifs', true, 68, true),
  ('GRAM-PT-14', 'PT', 'GRAMMAIRE', 'Le futur proche s''exprime avec "IR + infinitif" : "Vou esquiar amanhã".', NULL, false, 'Futur proche', true, 69, true),
  ('GRAM-PT-15', 'PT', 'GRAMMAIRE', 'Attention au passé : pretérito perfeito (action ponctuelle) vs imperfeito (habitude, description).', NULL, false, 'Passé', true, 70, true),
  ('GRAM-PT-16', 'PT', 'GRAMMAIRE', 'Vous mélangez le pretérito perfeito et l''imperfeito : révisez la différence.', NULL, true, 'Passé', false, 71, true),
  ('GRAM-PT-17', 'PT', 'GRAMMAIRE', 'Le conditionnel se forme avec -IA : "Eu gostaria de..." (j''aimerais...).', NULL, false, 'Conditionnel', true, 72, true),
  ('GRAM-PT-18', 'PT', 'GRAMMAIRE', '"Por" vs "Para" : "por" = à travers, par, à cause de / "para" = pour, vers (destination, but).', NULL, false, 'Por/Para', true, 73, true),
  ('GRAM-PT-19', 'PT', 'GRAMMAIRE', 'Vous confondez POR et PARA : révisez leurs usages respectifs.', NULL, true, 'Por/Para', false, 74, true),
  ('GRAM-PT-20', 'PT', 'GRAMMAIRE', 'Les articles sont obligatoires devant les possessifs en portugais européen, optionnels au Brésil.', NULL, false, 'Articles', true, 75, true),
  ('TECH-PT-V01', 'PT', 'VOCABULAIRE', 'Rappel : escola de esqui (école de ski), aula (cours), iniciante (débutant), intermediário (intermédiaire), avançado (confirmé).', 'Niveaux', false, NULL, true, 76, true),
  ('TECH-PT-V02', 'PT', 'VOCABULAIRE', 'Rappel : cunha/pizza (chasse-neige), curva paralela (virage parallèle), bastões (bâtons), lâminas (carres).', 'Technique', false, NULL, true, 77, true),
  ('TECH-PT-V03', 'PT', 'VOCABULAIRE', 'Rappel : dobre os joelhos (pliez les genoux), incline-se para frente (penchez-vous en avant), transferência de peso (transfert de poids).', 'Instructions', false, NULL, true, 78, true),
  ('TECH-PT-V04', 'PT', 'VOCABULAIRE', 'Rappel : teleférico/telecadeira (télésiège), teleférico de arrasto (téléski), gôndola (télécabine).', 'Remontées', false, NULL, true, 79, true),
  ('TECH-PT-V05', 'PT', 'VOCABULAIRE', 'Rappel : barra de segurança (garde-corps), apoio para os pés (repose-pieds), levante (lever), abaixe (baisser).', 'Remontées', false, NULL, true, 80, true),
  ('TECH-PT-V06', 'PT', 'VOCABULAIRE', 'Rappel : olhe em frente (regardez devant), siga-me (suivez-moi), pare aqui (arrêtez-vous ici), muito bem (bien joué).', 'Instructions', false, NULL, true, 81, true),
  ('TECH-PT-V07', 'PT', 'VOCABULAIRE', 'Rappel : pontas dos esquis (spatules), caudas dos esquis (talons), fixações (fixations), botas (chaussures).', 'Équipement', false, NULL, true, 82, true),
  ('TECH-PT-V08', 'PT', 'VOCABULAIRE', 'Rappel : pista (piste), pista verde (piste verte), fora de pista (hors-piste), moguls/lombadas (bosses).', 'Pistes', false, NULL, true, 83, true),
  ('TECH-PT-V09', 'PT', 'VOCABULAIRE', 'Rappel : estação de esqui (station de ski) - pas "estação" seul qui signifie gare ou saison.', 'Station', false, NULL, true, 84, true),
  ('TECH-PT-V10', 'PT', 'VOCABULAIRE', 'Rappel : Onde dói? (Où avez-vous mal?), Consegue se mexer? (Pouvez-vous bouger?), A ajuda está chegando (Les secours arrivent).', 'Urgence', false, NULL, true, 85, true),
  ('EXPR-ES-01', 'ES', 'PRONONCIATION', 'Le "J" espagnol est une jota gutturale, pas un "J" français : "jefe" se prononce avec un son de gorge.', NULL, false, 'Jota', true, 86, true),
  ('EXPR-ES-02', 'ES', 'PRONONCIATION', 'Votre "J" français est incompréhensible pour un hispanophone : travaillez la jota.', NULL, true, 'Jota', false, 87, true),
  ('EXPR-ES-03', 'ES', 'PRONONCIATION', 'Le "R" roulé (RR ou R initial) doit vibrer avec la langue contre le palais.', NULL, false, 'R roulé', true, 88, true),
  ('EXPR-ES-04', 'ES', 'PRONONCIATION', 'Le "R" roulé est absent de votre prononciation : c''est un point à travailler.', NULL, true, 'R roulé', false, 89, true),
  ('EXPR-ES-05', 'ES', 'PRONONCIATION', 'Le "Z" et le "C" (devant e/i) se prononcent "S" en Amérique latine, "TH" en Espagne.', NULL, false, 'Z/C', true, 90, true),
  ('EXPR-ES-06', 'ES', 'PRONONCIATION', 'Attention : le "V" se prononce comme un "B" doux en espagnol.', NULL, false, 'V = B', true, 91, true),
  ('EXPR-ES-07', 'ES', 'PRONONCIATION', 'Le "LL" se prononce "Y" dans la plupart des régions : "llamar" = "yamar".', NULL, false, 'LL', true, 92, true),
  ('EXPR-ES-08', 'ES', 'PRONONCIATION', 'Le "H" est toujours muet en espagnol : "hola" = "ola".', NULL, false, 'H muet', true, 93, true),
  ('EXPR-ES-09', 'ES', 'PRONONCIATION', 'Attention à l''accent tonique : en espagnol, il est crucial pour le sens (hablo vs habló).', NULL, false, 'Accent tonique', true, 94, true),
  ('EXPR-ES-10', 'ES', 'PRONONCIATION', 'Le "U" après "G" ou "Q" ne se prononce pas : "que" = "ké", "guitarra" = "gitara".', NULL, false, 'U muet', true, 95, true),
  ('GRAM-ES-01', 'ES', 'GRAMMAIRE', 'SER (permanent, identité) vs ESTAR (temporaire, état, lieu) : "Soy profesor" vs "Estoy cansado".', NULL, false, 'Ser/Estar', true, 96, true),
  ('GRAM-ES-02', 'ES', 'GRAMMAIRE', 'La distinction SER/ESTAR est fondamentale et vous la maîtrisez mal.', NULL, true, 'Ser/Estar', false, 97, true),
  ('GRAM-ES-03', 'ES', 'GRAMMAIRE', 'Le sujet est généralement omis en espagnol : "Hablo español" (pas "Yo hablo español").', NULL, false, 'Sujet omis', true, 98, true),
  ('GRAM-ES-04', 'ES', 'GRAMMAIRE', '"Gustar" fonctionne à l''envers : "Me gusta el esquí" (le ski me plaît) et non "Yo gusto el esquí".', NULL, false, 'Gustar', true, 99, true),
  ('GRAM-ES-05', 'ES', 'GRAMMAIRE', 'La structure de GUSTAR vous pose problème : le sujet français devient COI en espagnol.', NULL, true, 'Gustar', false, 100, true),
  ('GRAM-ES-06', 'ES', 'GRAMMAIRE', 'Les deux passés : pretérito indefinido (action ponctuelle) vs pretérito imperfecto (habitude, description).', NULL, false, 'Passé', true, 101, true),
  ('GRAM-ES-07', 'ES', 'GRAMMAIRE', 'Vous confondez les deux passés espagnols : révisez indefinido vs imperfecto.', NULL, true, 'Passé', false, 102, true),
  ('GRAM-ES-08', 'ES', 'GRAMMAIRE', 'Le subjonctif est très utilisé : après "querer que", "esperar que", "para que", etc.', NULL, false, 'Subjonctif', true, 103, true),
  ('GRAM-ES-09', 'ES', 'GRAMMAIRE', 'Le subjonctif espagnol est mal maîtrisé : il est plus fréquent qu''en français moderne.', NULL, true, 'Subjonctif', false, 104, true),
  ('GRAM-ES-10', 'ES', 'GRAMMAIRE', '"Hay" (il y a) est invariable : "Hay un problema" / "Hay muchos problemas".', NULL, false, 'Hay', true, 105, true),
  ('GRAM-ES-11', 'ES', 'GRAMMAIRE', 'POR vs PARA : "por" = à cause de, par, pendant / "para" = pour, vers, but.', NULL, false, 'Por/Para', true, 106, true),
  ('GRAM-ES-12', 'ES', 'GRAMMAIRE', 'POR et PARA sont souvent confondus dans vos phrases.', NULL, true, 'Por/Para', false, 107, true),
  ('GRAM-ES-13', 'ES', 'GRAMMAIRE', 'L''article défini s''utilise devant les noms de langues : "Hablo el español".', NULL, false, 'Articles', true, 108, true),
  ('GRAM-ES-14', 'ES', 'GRAMMAIRE', 'Le "a" personnel : devant un COD humain, ajoutez "a" : "Veo a mi alumno".', NULL, false, 'A personnel', true, 109, true),
  ('GRAM-ES-15', 'ES', 'GRAMMAIRE', 'Vous oubliez systématiquement le "a" personnel devant les COD humains.', NULL, true, 'A personnel', false, 110, true),
  ('GRAM-ES-16', 'ES', 'GRAMMAIRE', 'Les possessifs courts vont avant le nom : "mi esquí" (pas "el esquí mío" sauf emphase).', NULL, false, 'Possessifs', true, 111, true),
  ('GRAM-ES-17', 'ES', 'GRAMMAIRE', 'Le gérondif (-ANDO/-IENDO) exprime une action en cours : "Estoy esquiando".', NULL, false, 'Gérondif', true, 112, true),
  ('GRAM-ES-18', 'ES', 'GRAMMAIRE', 'Attention à "depuis" : "Llevo 5 años enseñando" ou "Enseño desde hace 5 años".', NULL, false, 'Depuis', true, 113, true),
  ('GRAM-ES-19', 'ES', 'GRAMMAIRE', 'Les pronoms COD/COI se placent avant le verbe conjugué ou attachés à l''infinitif/gérondif.', NULL, false, 'Pronoms', true, 114, true),
  ('GRAM-ES-20', 'ES', 'GRAMMAIRE', 'Le placement des pronoms est souvent incorrect dans vos phrases.', NULL, true, 'Pronoms', false, 115, true),
  ('TECH-ES-V01', 'ES', 'VOCABULAIRE', 'Rappel : escuela de esquí (école de ski), clase (cours), principiante (débutant), intermedio (intermédiaire), avanzado (confirmé).', 'Niveaux', false, NULL, true, 116, true),
  ('TECH-ES-V02', 'ES', 'VOCABULAIRE', 'Rappel : cuña (chasse-neige), giro paralelo (virage parallèle), bastones (bâtons), cantos (carres).', 'Technique', false, NULL, true, 117, true),
  ('TECH-ES-V03', 'ES', 'VOCABULAIRE', 'Rappel : flexiona las rodillas (pliez les genoux), inclínate hacia adelante (penchez-vous en avant), transferencia de peso (transfert de poids).', 'Instructions', false, NULL, true, 118, true),
  ('TECH-ES-V04', 'ES', 'VOCABULAIRE', 'Rappel : telesilla (télésiège), telearrastre (téléski), telecabina/góndola (télécabine).', 'Remontées', false, NULL, true, 119, true),
  ('TECH-ES-V05', 'ES', 'VOCABULAIRE', 'Rappel : barra de seguridad (garde-corps), reposapiés (repose-pieds), levanta (lever), baja (baisser).', 'Remontées', false, NULL, true, 120, true),
  ('TECH-ES-V06', 'ES', 'VOCABULAIRE', 'Rappel : mira adelante (regardez devant), sígueme (suivez-moi), para aquí (arrêtez-vous ici), muy bien (bien joué).', 'Instructions', false, NULL, true, 121, true),
  ('TECH-ES-V07', 'ES', 'VOCABULAIRE', 'Rappel : puntas de los esquís (spatules), colas (talons), fijaciones (fixations), botas (chaussures).', 'Équipement', false, NULL, true, 122, true),
  ('TECH-ES-V08', 'ES', 'VOCABULAIRE', 'Rappel : pista (piste), pista verde (piste verte), fuera de pista (hors-piste), baches/moguls (bosses).', 'Pistes', false, NULL, true, 123, true),
  ('TECH-ES-V09', 'ES', 'VOCABULAIRE', 'Rappel : estación de esquí (station de ski) - pas "estación" seul qui signifie gare ou saison.', 'Station', false, NULL, true, 124, true),
  ('TECH-ES-V10', 'ES', 'VOCABULAIRE', 'Rappel : ¿Dónde te duele? (Où as-tu mal?), ¿Puedes moverte? (Peux-tu bouger?), La ayuda viene en camino (Les secours arrivent).', 'Urgence', false, NULL, true, 125, true),
  ('EXPR-NL-01', 'NL', 'PRONONCIATION', 'Le "G" néerlandais est guttural (comme le "ch" allemand de "Bach") : pratiquez ce son de gorge.', NULL, false, 'G guttural', true, 126, true),
  ('EXPR-NL-02', 'NL', 'PRONONCIATION', 'Le "G" guttural néerlandais est absent de votre prononciation : c''est un son essentiel.', NULL, true, 'G guttural', false, 127, true),
  ('EXPR-NL-03', 'NL', 'PRONONCIATION', 'Le "CH" se prononce également de manière gutturale, comme le "G".', NULL, false, 'CH', true, 128, true),
  ('EXPR-NL-04', 'NL', 'PRONONCIATION', 'Le "R" néerlandais peut être roulé ou guttural selon les régions.', NULL, false, 'R', true, 129, true),
  ('EXPR-NL-05', 'NL', 'PRONONCIATION', 'Les voyelles longues et courtes sont distinctives : "man" (homme) vs "maan" (lune).', NULL, false, 'Voyelles', true, 130, true),
  ('EXPR-NL-06', 'NL', 'PRONONCIATION', 'Vous ne faites pas la distinction entre voyelles longues et courtes : c''est problématique.', NULL, true, 'Voyelles', false, 131, true),
  ('EXPR-NL-07', 'NL', 'PRONONCIATION', 'Le "W" se prononce entre un "V" et un "W" anglais.', NULL, false, 'W', true, 132, true),
  ('EXPR-NL-08', 'NL', 'PRONONCIATION', 'Le "IJ" et "EI" se prononcent comme un "AY" long.', NULL, false, 'IJ/EI', true, 133, true),
  ('EXPR-NL-09', 'NL', 'PRONONCIATION', 'Le "UI" est une diphtongue difficile, proche de "EU" suivi de "I".', NULL, false, 'UI', true, 134, true),
  ('EXPR-NL-10', 'NL', 'PRONONCIATION', 'Les consonnes finales se dévoisent : "hond" se prononce "hont".', NULL, false, 'Dévoisement', true, 135, true),
  ('GRAM-NL-01', 'NL', 'GRAMMAIRE', 'L''ordre des mots est V2 (verbe en 2e position) en phrase principale : "Vandaag ski ik" (Aujourd''hui, je skie).', NULL, false, 'Ordre V2', true, 136, true),
  ('GRAM-NL-02', 'NL', 'GRAMMAIRE', 'L''ordre des mots V2 n''est pas respecté : le verbe doit être en 2e position.', NULL, true, 'Ordre V2', false, 137, true),
  ('GRAM-NL-03', 'NL', 'GRAMMAIRE', 'En subordonnée, le verbe va à la fin : "omdat ik ski" (parce que je skie).', NULL, false, 'Subordonnée', true, 138, true),
  ('GRAM-NL-04', 'NL', 'GRAMMAIRE', 'En subordonnée, vous ne mettez pas le verbe à la fin comme il faut.', NULL, true, 'Subordonnée', false, 139, true),
  ('GRAM-NL-05', 'NL', 'GRAMMAIRE', 'Les verbes séparables : le préfixe va à la fin : "Ik sta op" (je me lève).', NULL, false, 'Verbes séparables', true, 140, true),
  ('GRAM-NL-06', 'NL', 'GRAMMAIRE', 'Les verbes séparables vous posent problème : le préfixe doit aller à la fin.', NULL, true, 'Verbes séparables', false, 141, true),
  ('GRAM-NL-07', 'NL', 'GRAMMAIRE', 'Deux genres : "de" (commun) et "het" (neutre). Il faut les apprendre par cœur.', NULL, false, 'Genres de/het', true, 142, true),
  ('GRAM-NL-08', 'NL', 'GRAMMAIRE', 'Vous mélangez "de" et "het" : apprenez le genre avec chaque nouveau mot.', NULL, true, 'Genres', false, 143, true),
  ('GRAM-NL-09', 'NL', 'GRAMMAIRE', 'L''adjectif prend un "-e" devant les noms définis et pluriels : "de grote berg" mais "een groot huis".', NULL, false, 'Adjectifs', true, 144, true),
  ('GRAM-NL-10', 'NL', 'GRAMMAIRE', 'Le passé composé utilise "hebben" ou "zijn" selon le verbe.', NULL, false, 'Auxiliaires', true, 145, true),
  ('GRAM-NL-11', 'NL', 'GRAMMAIRE', 'Les verbes de mouvement prennent "zijn" : "Ik ben geskied" (j''ai skié).', NULL, false, 'Zijn', true, 146, true),
  ('GRAM-NL-12', 'NL', 'GRAMMAIRE', 'Le diminutif (-je, -tje, -pje, -etje) est très utilisé : "huisje" (maisonnette).', NULL, false, 'Diminutifs', true, 147, true),
  ('GRAM-NL-13', 'NL', 'GRAMMAIRE', '"Er" a plusieurs fonctions (il y a, pronom, lieu) : "Er is sneeuw" (Il y a de la neige).', NULL, false, 'Er', true, 148, true),
  ('GRAM-NL-14', 'NL', 'GRAMMAIRE', 'La négation "niet" se place généralement en fin de phrase ou avant l''élément nié.', NULL, false, 'Négation', true, 149, true),
  ('GRAM-NL-15', 'NL', 'GRAMMAIRE', 'Le placement de "niet" est souvent incorrect dans vos phrases.', NULL, true, 'Négation', false, 150, true),
  ('GRAM-NL-16', 'NL', 'GRAMMAIRE', 'Les prépositions régissent parfois des cas : "met hem" (avec lui) vs "van hem" (de lui).', NULL, false, 'Prépositions', true, 151, true),
  ('TECH-NL-V01', 'NL', 'VOCABULAIRE', 'Rappel : skischool (école de ski), les (cours), beginner (débutant), gevorderde (intermédiaire), expert (confirmé).', 'Niveaux', false, NULL, true, 152, true),
  ('TECH-NL-V02', 'NL', 'VOCABULAIRE', 'Rappel : ploeg/pizzapunt (chasse-neige), parallelle bocht (virage parallèle), stokken (bâtons), kanten (carres).', 'Technique', false, NULL, true, 153, true),
  ('TECH-NL-V03', 'NL', 'VOCABULAIRE', 'Rappel : buig je knieën (pliez les genoux), leun voorover (penchez-vous en avant), gewichtsverplaatsing (transfert de poids).', 'Instructions', false, NULL, true, 154, true),
  ('TECH-NL-V04', 'NL', 'VOCABULAIRE', 'Rappel : stoeltjeslift (télésiège), sleeplift (téléski), gondel/cabine (télécabine).', 'Remontées', false, NULL, true, 155, true),
  ('TECH-NL-V05', 'NL', 'VOCABULAIRE', 'Rappel : veiligheidsbeugel (garde-corps), voetensteun (repose-pieds), omhoog (lever), omlaag (baisser).', 'Remontées', false, NULL, true, 156, true),
  ('TECH-NL-V06', 'NL', 'VOCABULAIRE', 'Rappel : kijk vooruit (regardez devant), volg mij (suivez-moi), stop hier (arrêtez-vous ici), goed gedaan (bien joué).', 'Instructions', false, NULL, true, 157, true),
  ('TECH-NL-V07', 'NL', 'VOCABULAIRE', 'Rappel : skipunten (spatules), skistaarten (talons), bindingen (fixations), skischoenen (chaussures).', 'Équipement', false, NULL, true, 158, true),
  ('TECH-NL-V08', 'NL', 'VOCABULAIRE', 'Rappel : piste (piste), groene piste (piste verte), off-piste (hors-piste), bulten (bosses).', 'Pistes', false, NULL, true, 159, true),
  ('TECH-NL-V09', 'NL', 'VOCABULAIRE', 'Rappel : skigebied (domaine skiable), skiresort (station de ski).', 'Station', false, NULL, true, 160, true),
  ('TECH-NL-V10', 'NL', 'VOCABULAIRE', 'Rappel : Waar doet het pijn? (Où avez-vous mal?), Kun je bewegen? (Pouvez-vous bouger?), Hulp is onderweg (Les secours arrivent).', 'Urgence', false, NULL, true, 161, true),
  ('EXPR-RU-01', 'RU', 'PRONONCIATION', 'Le "Ы" (y) est une voyelle difficile : positionnez la langue comme pour "i" mais reculée.', NULL, false, 'Ы', true, 162, true),
  ('EXPR-RU-02', 'RU', 'PRONONCIATION', 'Le son "Ы" est absent de votre prononciation : c''est un son essentiel en russe.', NULL, true, 'Ы', false, 163, true),
  ('EXPR-RU-03', 'RU', 'PRONONCIATION', 'Distinguez les consonnes dures et molles (palatalisées) : c''est phonémique en russe.', NULL, false, 'Consonnes molles', true, 164, true),
  ('EXPR-RU-04', 'RU', 'PRONONCIATION', 'Vous ne faites pas la différence entre consonnes dures et molles : travaillez ce point.', NULL, true, 'Consonnes molles', false, 165, true),
  ('EXPR-RU-05', 'RU', 'PRONONCIATION', 'Le "Р" russe est roulé comme en espagnol ou italien.', NULL, false, 'R roulé', true, 166, true),
  ('EXPR-RU-06', 'RU', 'PRONONCIATION', 'Le "Х" se prononce comme le "J" espagnol ou le "CH" allemand de "Bach".', NULL, false, 'Х', true, 167, true),
  ('EXPR-RU-07', 'RU', 'PRONONCIATION', 'Les voyelles non accentuées se réduisent : "О" non accentué → "A", "Е/Я" non accentué → "И".', NULL, false, 'Réduction vocalique', true, 168, true),
  ('EXPR-RU-08', 'RU', 'PRONONCIATION', 'L''accent tonique est mobile et distinctif : apprenez-le avec chaque mot.', NULL, false, 'Accent tonique', true, 169, true),
  ('EXPR-RU-09', 'RU', 'PRONONCIATION', 'Le "Щ" se prononce comme un "CH" long et mouillé.', NULL, false, 'Щ', true, 170, true),
  ('EXPR-RU-10', 'RU', 'PRONONCIATION', 'Les consonnes finales se dévoisent : "год" (année) se prononce "got".', NULL, false, 'Dévoisement', true, 171, true),
  ('GRAM-RU-01', 'RU', 'GRAMMAIRE', 'Le russe a 6 cas (nominatif, génitif, datif, accusatif, instrumental, prépositionnel).', NULL, false, 'Cas', true, 172, true),
  ('GRAM-RU-02', 'RU', 'GRAMMAIRE', 'La déclinaison des noms et adjectifs est mal maîtrisée : les cas sont essentiels.', NULL, true, 'Cas', false, 173, true),
  ('GRAM-RU-03', 'RU', 'GRAMMAIRE', 'Les verbes ont deux aspects : imperfectif (action en cours/habituelle) et perfectif (action achevée).', NULL, false, 'Aspects', true, 174, true),
  ('GRAM-RU-04', 'RU', 'GRAMMAIRE', 'Vous confondez les aspects verbaux : imperfectif vs perfectif est fondamental.', NULL, true, 'Aspects', false, 175, true),
  ('GRAM-RU-05', 'RU', 'GRAMMAIRE', 'Le verbe "être" au présent est généralement omis : "Я студент" (Je suis étudiant).', NULL, false, 'Être omis', true, 176, true),
  ('GRAM-RU-06', 'RU', 'GRAMMAIRE', 'Les verbes de mouvement distinguent aller à pied/en véhicule, une fois/habituellement.', NULL, false, 'Verbes mouvement', true, 177, true),
  ('GRAM-RU-07', 'RU', 'GRAMMAIRE', 'Les verbes de mouvement russes sont complexes et mal utilisés.', NULL, true, 'Verbes mouvement', false, 178, true),
  ('GRAM-RU-08', 'RU', 'GRAMMAIRE', 'L''adjectif s''accorde en genre, nombre et cas avec le nom.', NULL, false, 'Accord adjectif', true, 179, true),
  ('GRAM-RU-09', 'RU', 'GRAMMAIRE', 'Après les nombres 2-4, le nom est au génitif singulier ; après 5+, au génitif pluriel.', NULL, false, 'Nombres + cas', true, 180, true),
  ('GRAM-RU-10', 'RU', 'GRAMMAIRE', 'L''accord après les nombres vous pose problème : révisez les règles.', NULL, true, 'Nombres', false, 181, true),
  ('GRAM-RU-11', 'RU', 'GRAMMAIRE', 'Les prépositions régissent des cas spécifiques : "в" + accusatif (direction) vs "в" + prépositionnel (lieu).', NULL, false, 'Prépositions', true, 182, true),
  ('GRAM-RU-12', 'RU', 'GRAMMAIRE', 'Le passé s''accorde en genre avec le sujet : "он читал" (il lisait) vs "она читала" (elle lisait).', NULL, false, 'Passé + genre', true, 183, true),
  ('GRAM-RU-13', 'RU', 'GRAMMAIRE', 'L''ordre des mots est relativement libre grâce aux cas, mais l''information nouvelle va en fin.', NULL, false, 'Ordre des mots', true, 184, true),
  ('GRAM-RU-14', 'RU', 'GRAMMAIRE', '"У меня есть" (j''ai) : littéralement "chez moi il y a" - structure à mémoriser.', NULL, false, 'Avoir', true, 185, true),
  ('GRAM-RU-15', 'RU', 'GRAMMAIRE', 'La négation "не" se place directement avant le verbe ou l''élément nié.', NULL, false, 'Négation', true, 186, true),
  ('GRAM-RU-16', 'RU', 'GRAMMAIRE', 'Le génitif s''utilise après la négation : "У меня нет машины" (je n''ai pas de voiture).', NULL, false, 'Génitif + négation', true, 187, true),
  ('TECH-RU-V01', 'RU', 'VOCABULAIRE', 'Rappel : горнолыжная школа (école de ski), урок (cours), начинающий (débutant), средний уровень (intermédiaire), продвинутый (confirmé).', 'Niveaux', false, NULL, true, 188, true),
  ('TECH-RU-V02', 'RU', 'VOCABULAIRE', 'Rappel : плуг (chasse-neige), параллельный поворот (virage parallèle), палки (bâtons), канты (carres).', 'Technique', false, NULL, true, 189, true),
  ('TECH-RU-V03', 'RU', 'VOCABULAIRE', 'Rappel : согните колени (pliez les genoux), наклонитесь вперёд (penchez-vous en avant), перенос веса (transfert de poids).', 'Instructions', false, NULL, true, 190, true),
  ('TECH-RU-V04', 'RU', 'VOCABULAIRE', 'Rappel : кресельный подъёмник (télésiège), бугельный подъёмник (téléski), гондола (télécabine).', 'Remontées', false, NULL, true, 191, true),
  ('TECH-RU-V05', 'RU', 'VOCABULAIRE', 'Rappel : страховочная дуга (garde-corps), подножка (repose-pieds), поднять (lever), опустить (baisser).', 'Remontées', false, NULL, true, 192, true),
  ('TECH-RU-V06', 'RU', 'VOCABULAIRE', 'Rappel : смотрите вперёд (regardez devant), следуйте за мной (suivez-moi), остановитесь здесь (arrêtez-vous ici), молодец (bien joué).', 'Instructions', false, NULL, true, 193, true),
  ('TECH-RU-V07', 'RU', 'VOCABULAIRE', 'Rappel : носки лыж (spatules), пятки лыж (talons), крепления (fixations), ботинки (chaussures).', 'Équipement', false, NULL, true, 194, true),
  ('TECH-RU-V08', 'RU', 'VOCABULAIRE', 'Rappel : трасса/склон (piste), зелёная трасса (piste verte), внетрассовое катание (hors-piste), бугры (bosses).', 'Pistes', false, NULL, true, 195, true),
  ('TECH-RU-V09', 'RU', 'VOCABULAIRE', 'Rappel : горнолыжный курорт (station de ski).', 'Station', false, NULL, true, 196, true),
  ('TECH-RU-V10', 'RU', 'VOCABULAIRE', 'Rappel : Где болит? (Où avez-vous mal?), Вы можете двигаться? (Pouvez-vous bouger?), Помощь идёт (Les secours arrivent).', 'Urgence', false, NULL, true, 197, true),
  ('EXPR-IT-01', 'IT', 'PRONONCIATION', 'Les consonnes doubles sont plus longues : "palla" ≠ "pala". Marquez bien la durée.', NULL, false, 'Doubles', true, 198, true),
  ('EXPR-IT-02', 'IT', 'PRONONCIATION', 'Vous ne marquez pas les consonnes doubles : c''est pourtant distinctif en italien.', NULL, true, 'Doubles', false, 199, true),
  ('EXPR-IT-03', 'IT', 'PRONONCIATION', 'Le "R" italien est roulé avec la langue contre le palais.', NULL, false, 'R roulé', true, 200, true),
  ('EXPR-IT-04', 'IT', 'PRONONCIATION', 'Le "GLI" se prononce comme le "LL" espagnol ou le "LH" portugais (mouillé).', NULL, false, 'GLI', true, 201, true),
  ('EXPR-IT-05', 'IT', 'PRONONCIATION', 'Le "GN" se prononce comme en français ("montagne").', NULL, false, 'GN', true, 202, true),
  ('EXPR-IT-06', 'IT', 'PRONONCIATION', 'Le "C" devant E/I se prononce "TCH" : "ciao" = "tchao".', NULL, false, 'C + e/i', true, 203, true),
  ('EXPR-IT-07', 'IT', 'PRONONCIATION', 'Le "G" devant E/I se prononce "DJ" : "gelato" = "djelato".', NULL, false, 'G + e/i', true, 204, true),
  ('EXPR-IT-08', 'IT', 'PRONONCIATION', 'Le "SC" devant E/I se prononce "CH" : "sci" = "chi".', NULL, false, 'SC + e/i', true, 205, true),
  ('EXPR-IT-09', 'IT', 'PRONONCIATION', 'Le "H" est toujours muet et sert à durcir C et G : "che" = "ké", "ghetto" = "guetto".', NULL, false, 'H muet', true, 206, true),
  ('EXPR-IT-10', 'IT', 'PRONONCIATION', 'L''accent tonique varie : apprenez-le avec chaque mot.', NULL, false, 'Accent tonique', true, 207, true),
  ('GRAM-IT-01', 'IT', 'GRAMMAIRE', 'Le sujet est généralement omis : "Parlo italiano" (pas "Io parlo italiano").', NULL, false, 'Sujet omis', true, 208, true),
  ('GRAM-IT-02', 'IT', 'GRAMMAIRE', 'Les articles définis : il/lo/la/i/gli/le - "lo" devant s+consonne, z, gn, ps, x.', NULL, false, 'Articles', true, 209, true),
  ('GRAM-IT-03', 'IT', 'GRAMMAIRE', 'Vous utilisez mal les articles "il" et "lo" : révisez les règles.', NULL, true, 'Articles', false, 210, true),
  ('GRAM-IT-04', 'IT', 'GRAMMAIRE', 'Les articles contractés : a+il=al, di+il=del, in+il=nel, etc.', NULL, false, 'Contractions', true, 211, true),
  ('GRAM-IT-05', 'IT', 'GRAMMAIRE', 'Passato prossimo vs imperfetto : comme en français, mais l''imparfait est plus utilisé en italien.', NULL, false, 'Passé', true, 212, true),
  ('GRAM-IT-06', 'IT', 'GRAMMAIRE', 'Le passato prossimo utilise "essere" ou "avere" selon le verbe.', NULL, false, 'Auxiliaires', true, 213, true),
  ('GRAM-IT-07', 'IT', 'GRAMMAIRE', 'Avec "essere", le participe s''accorde : "Maria è andata" (Marie est allée).', NULL, false, 'Accord participe', true, 214, true),
  ('GRAM-IT-08', 'IT', 'GRAMMAIRE', 'L''accord du participe passé avec essere est souvent oublié.', NULL, true, 'Accord participe', false, 215, true),
  ('GRAM-IT-09', 'IT', 'GRAMMAIRE', '"Piacere" fonctionne comme "gustar" espagnol : "Mi piace lo sci" (le ski me plaît).', NULL, false, 'Piacere', true, 216, true),
  ('GRAM-IT-10', 'IT', 'GRAMMAIRE', 'La structure de PIACERE vous pose problème : le sujet français devient COI.', NULL, true, 'Piacere', false, 217, true),
  ('GRAM-IT-11', 'IT', 'GRAMMAIRE', 'Le subjonctif est très utilisé après "che", "penso che", "voglio che", etc.', NULL, false, 'Subjonctif', true, 218, true),
  ('GRAM-IT-12', 'IT', 'GRAMMAIRE', 'Le subjonctif italien est mal maîtrisé : il est plus fréquent qu''en français moderne.', NULL, true, 'Subjonctif', false, 219, true),
  ('GRAM-IT-13', 'IT', 'GRAMMAIRE', '"C''è" (il y a, singulier) / "Ci sono" (il y a, pluriel).', NULL, false, 'C''è/Ci sono', true, 220, true),
  ('GRAM-IT-14', 'IT', 'GRAMMAIRE', 'Les possessifs prennent l''article : "il mio sci" (mon ski) - sauf avec les noms de famille au singulier.', NULL, false, 'Possessifs', true, 221, true),
  ('GRAM-IT-15', 'IT', 'GRAMMAIRE', 'Le conditionnel se forme avec -EI, -ESTI, -EBBE... : "Vorrei..." (je voudrais).', NULL, false, 'Conditionnel', true, 222, true),
  ('GRAM-IT-16', 'IT', 'GRAMMAIRE', 'Les pronoms COD/COI se placent avant le verbe conjugué ou attachés à l''infinitif.', NULL, false, 'Pronoms', true, 223, true),
  ('GRAM-IT-17', 'IT', 'GRAMMAIRE', 'Le placement des pronoms est souvent incorrect.', NULL, true, 'Pronoms', false, 224, true),
  ('GRAM-IT-18', 'IT', 'GRAMMAIRE', '"Stare + gérondif" pour l''action en cours : "Sto sciando" (je suis en train de skier).', NULL, false, 'Gérondif', true, 225, true),
  ('GRAM-IT-19', 'IT', 'GRAMMAIRE', 'Attention aux faux amis : "camera" = chambre (pas caméra), "salire" = monter (pas salir).', NULL, false, 'Faux amis', true, 226, true),
  ('TECH-IT-V01', 'IT', 'VOCABULAIRE', 'Rappel : scuola di sci (école de ski), lezione (cours), principiante (débutant), intermedio (intermédiaire), esperto (confirmé).', 'Niveaux', false, NULL, true, 227, true),
  ('TECH-IT-V02', 'IT', 'VOCABULAIRE', 'Rappel : spazzaneve (chasse-neige), curva parallela (virage parallèle), bastoncini (bâtons), lamine (carres).', 'Technique', false, NULL, true, 228, true),
  ('TECH-IT-V03', 'IT', 'VOCABULAIRE', 'Rappel : piega le ginocchia (pliez les genoux), piegati in avanti (penchez-vous en avant), trasferimento del peso (transfert de poids).', 'Instructions', false, NULL, true, 229, true),
  ('TECH-IT-V04', 'IT', 'VOCABULAIRE', 'Rappel : seggiovia (télésiège), skilift (téléski), cabinovia/telecabina (télécabine).', 'Remontées', false, NULL, true, 230, true),
  ('TECH-IT-V05', 'IT', 'VOCABULAIRE', 'Rappel : barra di sicurezza (garde-corps), poggiapiedi (repose-pieds), alzare (lever), abbassare (baisser).', 'Remontées', false, NULL, true, 231, true),
  ('TECH-IT-V06', 'IT', 'VOCABULAIRE', 'Rappel : guarda avanti (regardez devant), seguimi (suivez-moi), fermati qui (arrêtez-vous ici), bravo/brava (bien joué).', 'Instructions', false, NULL, true, 232, true),
  ('TECH-IT-V07', 'IT', 'VOCABULAIRE', 'Rappel : punte degli sci (spatules), code degli sci (talons), attacchi (fixations), scarponi (chaussures).', 'Équipement', false, NULL, true, 233, true),
  ('TECH-IT-V08', 'IT', 'VOCABULAIRE', 'Rappel : pista (piste), pista verde (piste verte), fuoripista (hors-piste), gobbe (bosses).', 'Pistes', false, NULL, true, 234, true),
  ('TECH-IT-V09', 'IT', 'VOCABULAIRE', 'Rappel : stazione sciistica / comprensorio (station de ski / domaine).', 'Station', false, NULL, true, 235, true),
  ('TECH-IT-V10', 'IT', 'VOCABULAIRE', 'Rappel : Dove ti fa male? (Où as-tu mal?), Riesci a muoverti? (Tu arrives à bouger?), I soccorsi stanno arrivando (Les secours arrivent).', 'Urgence', false, NULL, true, 236, true),
  ('EXPR-ZH-01', 'ZH', 'PRONONCIATION', 'Les 4 tons sont essentiels en chinois : un mauvais ton = un autre mot. Pratiquez-les systématiquement.', NULL, false, 'Tons', true, 237, true),
  ('EXPR-ZH-02', 'ZH', 'PRONONCIATION', 'Les tons sont très mal maîtrisés : sans tons corrects, vous êtes difficilement compréhensible.', NULL, true, 'Tons', false, 238, true),
  ('EXPR-ZH-03', 'ZH', 'PRONONCIATION', 'Le 3ème ton descend puis remonte ; le 4ème ton descend brusquement.', NULL, false, 'Tons 3 et 4', true, 239, true),
  ('EXPR-ZH-04', 'ZH', 'PRONONCIATION', 'Le "X" (pinyin) se prononce comme un "S" chuinté, langue derrière les dents.', NULL, false, 'X', true, 240, true),
  ('EXPR-ZH-05', 'ZH', 'PRONONCIATION', 'Le "Q" (pinyin) se prononce comme un "TCH" aspiré, pas comme un "K".', NULL, false, 'Q', true, 241, true),
  ('EXPR-ZH-06', 'ZH', 'PRONONCIATION', 'Le "ZH" se prononce comme un "DJ" rétroflexe (langue recourbée).', NULL, false, 'ZH', true, 242, true),
  ('EXPR-ZH-07', 'ZH', 'PRONONCIATION', 'Le "R" chinois est une approximante rétroflexe, différente du R français.', NULL, false, 'R', true, 243, true),
  ('EXPR-ZH-08', 'ZH', 'PRONONCIATION', 'Distinguez les consonnes aspirées (p, t, k, c, ch, q) des non-aspirées (b, d, g, z, zh, j).', NULL, false, 'Aspiration', true, 244, true),
  ('EXPR-ZH-09', 'ZH', 'PRONONCIATION', 'Vous ne faites pas la différence entre consonnes aspirées et non-aspirées.', NULL, true, 'Aspiration', false, 245, true),
  ('EXPR-ZH-10', 'ZH', 'PRONONCIATION', 'Le "Ü" (pinyin) est comme le "u" français, mais le "U" simple est plus postérieur.', NULL, false, 'Ü vs U', true, 246, true),
  ('GRAM-ZH-01', 'ZH', 'GRAMMAIRE', 'Le chinois n''a pas de conjugaison : le verbe reste invariable (我滑雪 wǒ huáxuě = je skie).', NULL, false, 'Pas de conjugaison', true, 247, true),
  ('GRAM-ZH-02', 'ZH', 'GRAMMAIRE', 'L''ordre des mots est Sujet + Temps + Lieu + Verbe + Objet.', NULL, false, 'Ordre des mots', true, 248, true),
  ('GRAM-ZH-03', 'ZH', 'GRAMMAIRE', 'L''ordre des mots chinois est différent du français : le temps et le lieu vont AVANT le verbe.', NULL, true, 'Ordre des mots', false, 249, true),
  ('GRAM-ZH-04', 'ZH', 'GRAMMAIRE', 'Les classificateurs (量词) sont obligatoires entre nombre/démonstratif et nom : 一个人 yī gè rén (une personne).', NULL, false, 'Classificateurs', true, 250, true),
  ('GRAM-ZH-05', 'ZH', 'GRAMMAIRE', 'Les classificateurs sont souvent oubliés ou mal choisis.', NULL, true, 'Classificateurs', false, 251, true),
  ('GRAM-ZH-06', 'ZH', 'GRAMMAIRE', 'Le passé se marque avec 了 (le) après le verbe pour l''action accomplie : 我滑了雪 (j''ai skié).', NULL, false, '了 (le)', true, 252, true),
  ('GRAM-ZH-07', 'ZH', 'GRAMMAIRE', 'L''action en cours se marque avec 在 (zài) avant le verbe : 我在滑雪 (je suis en train de skier).', NULL, false, '在 (zài)', true, 253, true),
  ('GRAM-ZH-08', 'ZH', 'GRAMMAIRE', 'L''expérience passée se marque avec 过 (guò) : 我滑过雪 (j''ai déjà skié dans ma vie).', NULL, false, '过 (guò)', true, 254, true),
  ('GRAM-ZH-09', 'ZH', 'GRAMMAIRE', 'Vous confondez 了, 过 et 在 : ce sont trois aspects différents.', NULL, true, 'Aspects', false, 255, true),
  ('GRAM-ZH-10', 'ZH', 'GRAMMAIRE', 'La négation au présent : 不 (bù) ; la négation au passé : 没 (méi).', NULL, false, 'Négation', true, 256, true),
  ('GRAM-ZH-11', 'ZH', 'GRAMMAIRE', 'Vous utilisez 不 au lieu de 没 pour les actions passées.', NULL, true, '不 vs 没', false, 257, true),
  ('GRAM-ZH-12', 'ZH', 'GRAMMAIRE', 'Les questions se forment avec 吗 (ma) à la fin ou en répétant le verbe (affirmative + négative).', NULL, false, 'Questions', true, 258, true),
  ('GRAM-ZH-13', 'ZH', 'GRAMMAIRE', 'Le complément de résultat se place après le verbe : 学会 (xuéhuì) = apprendre jusqu''à savoir.', NULL, false, 'Compléments', true, 259, true),
  ('GRAM-ZH-14', 'ZH', 'GRAMMAIRE', 'Le comparatif : A 比 B + adjectif (A bǐ B = A est plus... que B).', NULL, false, 'Comparatif', true, 260, true),
  ('GRAM-ZH-15', 'ZH', 'GRAMMAIRE', '"Il y a" = 有 (yǒu) : 这里有雪 (zhèlǐ yǒu xuě = il y a de la neige ici).', NULL, false, '有 (yǒu)', true, 261, true),
  ('GRAM-ZH-16', 'ZH', 'GRAMMAIRE', 'Le thème se place souvent en début de phrase : 滑雪，我很喜欢 (Le ski, j''aime beaucoup).', NULL, false, 'Thématisation', true, 262, true),
  ('TECH-ZH-V01', 'ZH', 'VOCABULAIRE', 'Rappel : 滑雪学校 huáxuě xuéxiào (école de ski), 课 kè (cours), 初学者 chūxuézhě (débutant), 中级 zhōngjí (intermédiaire), 高级 gāojí (confirmé).', 'Niveaux', false, NULL, true, 263, true),
  ('TECH-ZH-V02', 'ZH', 'VOCABULAIRE', 'Rappel : 犁式 lí shì (chasse-neige), 平行转弯 píngxíng zhuǎnwān (virage parallèle), 雪杖 xuězhàng (bâtons), 雪板边刃 xuěbǎn biānrèn (carres).', 'Technique', false, NULL, true, 264, true),
  ('TECH-ZH-V03', 'ZH', 'VOCABULAIRE', 'Rappel : 弯曲膝盖 wānqū xīgài (pliez les genoux), 身体前倾 shēntǐ qiánqīng (penchez-vous en avant).', 'Instructions', false, NULL, true, 265, true),
  ('TECH-ZH-V04', 'ZH', 'VOCABULAIRE', 'Rappel : 缆车 lǎnchē (télésiège/télécabine), 拖牵 tuōqiān (téléski).', 'Remontées', false, NULL, true, 266, true),
  ('TECH-ZH-V05', 'ZH', 'VOCABULAIRE', 'Rappel : 安全杆 ānquán gǎn (garde-corps), 抬起 táiqǐ (lever), 放下 fàngxià (baisser).', 'Remontées', false, NULL, true, 267, true),
  ('TECH-ZH-V06', 'ZH', 'VOCABULAIRE', 'Rappel : 向前看 xiàng qián kàn (regardez devant), 跟我来 gēn wǒ lái (suivez-moi), 在这里停 zài zhèlǐ tíng (arrêtez-vous ici), 很好 hěn hǎo (bien joué).', 'Instructions', false, NULL, true, 268, true),
  ('TECH-ZH-V07', 'ZH', 'VOCABULAIRE', 'Rappel : 雪板头 xuěbǎn tóu (spatules), 雪板尾 xuěbǎn wěi (talons), 固定器 gùdìngqì (fixations), 雪鞋 xuěxié (chaussures).', 'Équipement', false, NULL, true, 269, true),
  ('TECH-ZH-V08', 'ZH', 'VOCABULAIRE', 'Rappel : 雪道 xuědào (piste), 绿道 lǜdào (piste verte), 野雪 yě xuě (hors-piste).', 'Pistes', false, NULL, true, 270, true),
  ('TECH-ZH-V09', 'ZH', 'VOCABULAIRE', 'Rappel : 滑雪场 huáxuěchǎng (station de ski).', 'Station', false, NULL, true, 271, true),
  ('TECH-ZH-V10', 'ZH', 'VOCABULAIRE', 'Rappel : 哪里疼？nǎlǐ téng? (Où avez-vous mal?), 你能动吗？nǐ néng dòng ma? (Pouvez-vous bouger?), 救援马上到 jiùyuán mǎshàng dào (Les secours arrivent).', 'Urgence', false, NULL, true, 272, true),
  ('EXPR-DE-01', 'DE', 'PRONONCIATION', 'Le "CH" après a/o/u est guttural (comme "Bach") ; après e/i/ä/ö/ü, il est palatal (comme "ich").', NULL, false, 'CH', true, 273, true),
  ('EXPR-DE-02', 'DE', 'PRONONCIATION', 'Le son "CH" allemand est mal prononcé : distinguez le "ach-Laut" du "ich-Laut".', NULL, true, 'CH', false, 274, true),
  ('EXPR-DE-03', 'DE', 'PRONONCIATION', 'Le "R" allemand est uvulaire (comme en français) ou roulé selon les régions.', NULL, false, 'R', true, 275, true),
  ('EXPR-DE-04', 'DE', 'PRONONCIATION', 'Les voyelles longues et courtes sont distinctives : "Staat" (état) vs "Stadt" (ville).', NULL, false, 'Voyelles', true, 276, true),
  ('EXPR-DE-05', 'DE', 'PRONONCIATION', 'Vous ne distinguez pas les voyelles longues des voyelles courtes.', NULL, true, 'Voyelles', false, 277, true),
  ('EXPR-DE-06', 'DE', 'PRONONCIATION', 'Les "Umlaute" (ä, ö, ü) sont des sons distincts, pas des variantes.', NULL, false, 'Umlaute', true, 278, true),
  ('EXPR-DE-07', 'DE', 'PRONONCIATION', 'Le "W" se prononce "V" : "Wasser" = "Vasser".', NULL, false, 'W = V', true, 279, true),
  ('EXPR-DE-08', 'DE', 'PRONONCIATION', 'Le "V" se prononce "F" dans les mots allemands : "Vater" = "Fater".', NULL, false, 'V = F', true, 280, true),
  ('EXPR-DE-09', 'DE', 'PRONONCIATION', 'Le "Z" se prononce "TS" : "Zeit" = "Tsaït".', NULL, false, 'Z = TS', true, 281, true),
  ('EXPR-DE-10', 'DE', 'PRONONCIATION', 'Le "S" initial devant voyelle se prononce "Z" : "Sonne" = "Zonne".', NULL, false, 'S = Z', true, 282, true),
  ('EXPR-DE-11', 'DE', 'PRONONCIATION', 'Le "ß" (Eszett) se prononce comme un "S" sourd long.', NULL, false, 'ß', true, 283, true),
  ('EXPR-DE-12', 'DE', 'PRONONCIATION', 'L''accent tonique est généralement sur la première syllabe des mots allemands.', NULL, false, 'Accent', true, 284, true),
  ('GRAM-DE-01', 'DE', 'GRAMMAIRE', 'L''allemand a 4 cas : nominatif, accusatif, datif, génitif. Les articles et adjectifs se déclinent.', NULL, false, 'Cas', true, 285, true),
  ('GRAM-DE-02', 'DE', 'GRAMMAIRE', 'La déclinaison des articles et adjectifs est mal maîtrisée : les cas sont essentiels.', NULL, true, 'Cas', false, 286, true),
  ('GRAM-DE-03', 'DE', 'GRAMMAIRE', 'En phrase principale, le verbe conjugué est TOUJOURS en 2ème position (V2).', NULL, false, 'Ordre V2', true, 287, true),
  ('GRAM-DE-04', 'DE', 'GRAMMAIRE', 'Le verbe n''est pas en 2ème position : c''est une règle absolue en allemand.', NULL, true, 'Ordre V2', false, 288, true),
  ('GRAM-DE-05', 'DE', 'GRAMMAIRE', 'En subordonnée, le verbe conjugué va à la FIN : "weil ich Ski fahre" (parce que je skie).', NULL, false, 'Subordonnée', true, 289, true),
  ('GRAM-DE-06', 'DE', 'GRAMMAIRE', 'En subordonnée, vous ne mettez pas le verbe à la fin.', NULL, true, 'Subordonnée', false, 290, true),
  ('GRAM-DE-07', 'DE', 'GRAMMAIRE', 'Les verbes séparables : le préfixe va à la fin : "Ich stehe auf" (je me lève).', NULL, false, 'Verbes séparables', true, 291, true),
  ('GRAM-DE-08', 'DE', 'GRAMMAIRE', 'Les verbes séparables vous posent problème : le préfixe doit aller à la fin.', NULL, true, 'Verbes séparables', false, 292, true),
  ('GRAM-DE-09', 'DE', 'GRAMMAIRE', 'Trois genres : der (masculin), die (féminin), das (neutre). Apprenez-les avec chaque nom.', NULL, false, 'Genres', true, 293, true),
  ('GRAM-DE-10', 'DE', 'GRAMMAIRE', 'Vous vous trompez souvent sur le genre des noms : apprenez der/die/das avec chaque mot.', NULL, true, 'Genres', false, 294, true),
  ('GRAM-DE-11', 'DE', 'GRAMMAIRE', 'Le parfait (Perfekt) utilise "haben" ou "sein" selon le verbe.', NULL, false, 'Auxiliaires', true, 295, true),
  ('GRAM-DE-12', 'DE', 'GRAMMAIRE', 'Les verbes de mouvement et de changement d''état prennent "sein" : "Ich bin gefahren".', NULL, false, 'Sein', true, 296, true),
  ('GRAM-DE-13', 'DE', 'GRAMMAIRE', 'L''accusatif répond à "wen/was?" (qui/quoi?) ; le datif à "wem?" (à qui?).', NULL, false, 'Accusatif/Datif', true, 297, true),
  ('GRAM-DE-14', 'DE', 'GRAMMAIRE', 'Vous confondez accusatif et datif : c''est un point fondamental.', NULL, true, 'Accusatif/Datif', false, 298, true),
  ('GRAM-DE-15', 'DE', 'GRAMMAIRE', 'Certaines prépositions régissent toujours le même cas : mit, zu, von → datif ; für, durch → accusatif.', NULL, false, 'Prépositions', true, 299, true),
  ('GRAM-DE-16', 'DE', 'GRAMMAIRE', 'Les prépositions de lieu : accusatif (direction) vs datif (position) : "in den Berg" vs "in dem Berg".', NULL, false, 'Prépositions lieu', true, 300, true),
  ('GRAM-DE-17', 'DE', 'GRAMMAIRE', 'L''adjectif épithète se décline : "ein großer Berg" vs "der große Berg" vs "großer Berg".', NULL, false, 'Déclinaison adj.', true, 301, true),
  ('GRAM-DE-18', 'DE', 'GRAMMAIRE', 'La déclinaison de l''adjectif est approximative : révisez les trois types de déclinaison.', NULL, true, 'Déclinaison adj.', false, 302, true),
  ('GRAM-DE-19', 'DE', 'GRAMMAIRE', 'Le conditionnel se forme avec "würde + infinitif" ou le Konjunktiv II.', NULL, false, 'Conditionnel', true, 303, true),
  ('GRAM-DE-20', 'DE', 'GRAMMAIRE', 'La négation "nicht" se place généralement en fin de phrase ou avant l''élément nié.', NULL, false, 'Négation', true, 304, true),
  ('TECH-DE-V01', 'DE', 'VOCABULAIRE', 'Rappel : Skischule (école de ski), Unterricht/Kurs (cours), Anfänger (débutant), Fortgeschrittener (intermédiaire), Experte (confirmé).', 'Niveaux', false, NULL, true, 305, true),
  ('TECH-DE-V02', 'DE', 'VOCABULAIRE', 'Rappel : Pflug/Schneepflug (chasse-neige), Parallelschwung (virage parallèle), Stöcke (bâtons), Kanten (carres).', 'Technique', false, NULL, true, 306, true),
  ('TECH-DE-V03', 'DE', 'VOCABULAIRE', 'Rappel : Knie beugen (pliez les genoux), nach vorne lehnen (penchez-vous en avant), Gewichtsverlagerung (transfert de poids).', 'Instructions', false, NULL, true, 307, true),
  ('TECH-DE-V04', 'DE', 'VOCABULAIRE', 'Rappel : Sessellift (télésiège), Schlepplift (téléski), Gondel/Kabinenbahn (télécabine).', 'Remontées', false, NULL, true, 308, true),
  ('TECH-DE-V05', 'DE', 'VOCABULAIRE', 'Rappel : Sicherheitsbügel (garde-corps), Fußstütze (repose-pieds), hochheben (lever), runterlassen (baisser).', 'Remontées', false, NULL, true, 309, true),
  ('TECH-DE-V06', 'DE', 'VOCABULAIRE', 'Rappel : nach vorne schauen (regardez devant), folgen Sie mir (suivez-moi), hier anhalten (arrêtez-vous ici), gut gemacht (bien joué).', 'Instructions', false, NULL, true, 310, true),
  ('TECH-DE-V07', 'DE', 'VOCABULAIRE', 'Rappel : Skispitzen (spatules), Skienden (talons), Bindungen (fixations), Skischuhe (chaussures).', 'Équipement', false, NULL, true, 311, true),
  ('TECH-DE-V08', 'DE', 'VOCABULAIRE', 'Rappel : Piste (piste), grüne Piste (piste verte), Tiefschnee/Off-Piste (hors-piste), Buckel (bosses).', 'Pistes', false, NULL, true, 312, true),
  ('TECH-DE-V09', 'DE', 'VOCABULAIRE', 'Rappel : Skigebiet (domaine skiable), Skiort (station de ski).', 'Station', false, NULL, true, 313, true),
  ('TECH-DE-V10', 'DE', 'VOCABULAIRE', 'Rappel : Wo tut es weh? (Où avez-vous mal?), Können Sie sich bewegen? (Pouvez-vous bouger?), Hilfe ist unterwegs (Les secours arrivent).', 'Urgence', false, NULL, true, 314, true),
  ('EXPR-FR-01', 'FR', 'PRONONCIATION', 'Les voyelles nasales (an, on, in, un) sont bien distinguées.', NULL, false, 'Nasales', true, 315, true),
  ('EXPR-FR-02', 'FR', 'PRONONCIATION', 'Les voyelles nasales sont mal prononcées ou confondues entre elles.', NULL, true, 'Nasales', false, 316, true),
  ('EXPR-FR-03', 'FR', 'PRONONCIATION', 'Le "R" français (uvulaire) est correctement produit.', NULL, false, 'R', true, 317, true),
  ('EXPR-FR-04', 'FR', 'PRONONCIATION', 'Le "R" français n''est pas maîtrisé : il est roulé ou absent.', NULL, true, 'R', false, 318, true),
  ('EXPR-FR-05', 'FR', 'PRONONCIATION', 'Le "U" français [y] est distinct du "OU" [u].', NULL, false, 'U vs OU', true, 319, true),
  ('EXPR-FR-06', 'FR', 'PRONONCIATION', 'Vous confondez le "U" et le "OU" français.', NULL, true, 'U vs OU', false, 320, true),
  ('EXPR-FR-07', 'FR', 'PRONONCIATION', 'Les liaisons obligatoires sont respectées.', NULL, false, 'Liaisons', true, 321, true),
  ('EXPR-FR-08', 'FR', 'PRONONCIATION', 'Les liaisons obligatoires sont souvent omises.', NULL, true, 'Liaisons', false, 322, true),
  ('EXPR-FR-09', 'FR', 'PRONONCIATION', 'L''enchaînement vocalique est fluide.', NULL, false, 'Enchaînement', true, 323, true),
  ('EXPR-FR-10', 'FR', 'PRONONCIATION', 'Les "e" muets sont correctement gérés.', NULL, false, 'E muet', true, 324, true),
  ('EXPR-FR-11', 'FR', 'PRONONCIATION', 'L''intonation française (montante pour les questions) est respectée.', NULL, false, 'Intonation', true, 325, true),
  ('EXPR-FR-12', 'FR', 'PRONONCIATION', 'Votre intonation reste celle de votre langue maternelle.', NULL, true, 'Intonation', false, 326, true),
  ('GRAM-FR-01', 'FR', 'GRAMMAIRE', 'L''accord du participe passé avec avoir + COD antéposé est correct.', NULL, false, 'Accord PP', true, 327, true),
  ('GRAM-FR-02', 'FR', 'GRAMMAIRE', 'L''accord du participe passé est mal maîtrisé.', NULL, true, 'Accord PP', false, 328, true),
  ('GRAM-FR-03', 'FR', 'GRAMMAIRE', 'Le subjonctif est utilisé correctement après les verbes de volonté, doute, émotion.', NULL, false, 'Subjonctif', true, 329, true),
  ('GRAM-FR-04', 'FR', 'GRAMMAIRE', 'Le subjonctif est souvent remplacé par l''indicatif.', NULL, true, 'Subjonctif', false, 330, true),
  ('GRAM-FR-05', 'FR', 'GRAMMAIRE', 'La concordance des temps est respectée.', NULL, false, 'Concordance', true, 331, true),
  ('GRAM-FR-06', 'FR', 'GRAMMAIRE', 'La concordance des temps n''est pas respectée dans le discours indirect.', NULL, true, 'Concordance', false, 332, true),
  ('GRAM-FR-07', 'FR', 'GRAMMAIRE', 'Les pronoms COD et COI sont correctement placés et accordés.', NULL, false, 'Pronoms', true, 333, true),
  ('GRAM-FR-08', 'FR', 'GRAMMAIRE', 'Le placement des pronoms est incorrect.', NULL, true, 'Pronoms', false, 334, true),
  ('GRAM-FR-09', 'FR', 'GRAMMAIRE', 'La négation est complète (ne...pas, ne...plus, ne...jamais).', NULL, false, 'Négation', true, 335, true),
  ('GRAM-FR-10', 'FR', 'GRAMMAIRE', 'Le "ne" de la négation est systématiquement oublié.', NULL, true, 'Négation', false, 336, true),
  ('GRAM-FR-11', 'FR', 'GRAMMAIRE', 'Les articles partitifs (du, de la, des) sont correctement utilisés.', NULL, false, 'Partitifs', true, 337, true),
  ('GRAM-FR-12', 'FR', 'GRAMMAIRE', 'Les articles partitifs sont mal utilisés ou absents.', NULL, true, 'Partitifs', false, 338, true),
  ('GRAM-FR-13', 'FR', 'GRAMMAIRE', 'Les prépositions de lieu sont correctes (à, en, au, aux).', NULL, false, 'Prépositions', true, 339, true),
  ('GRAM-FR-14', 'FR', 'GRAMMAIRE', 'Les prépositions de lieu sont souvent incorrectes.', NULL, true, 'Prépositions', false, 340, true),
  ('GRAM-FR-15', 'FR', 'GRAMMAIRE', 'Le genre des noms est généralement correct.', NULL, false, 'Genre', true, 341, true),
  ('GRAM-FR-16', 'FR', 'GRAMMAIRE', 'Le genre des noms est souvent incorrect.', NULL, true, 'Genre', false, 342, true),
  ('GRAM-FR-17', 'FR', 'GRAMMAIRE', 'Le passé composé et l''imparfait sont correctement distingués.', NULL, false, 'PC vs Imparfait', true, 343, true),
  ('GRAM-FR-18', 'FR', 'GRAMMAIRE', 'Le passé composé et l''imparfait sont confondus.', NULL, true, 'PC vs Imparfait', false, 344, true),
  ('GRAM-FR-19', 'FR', 'GRAMMAIRE', 'L''accord de l''adjectif en genre et nombre est respecté.', NULL, false, 'Accord adj.', true, 345, true),
  ('GRAM-FR-20', 'FR', 'GRAMMAIRE', 'L''accord de l''adjectif est souvent oublié ou incorrect.', NULL, true, 'Accord adj.', false, 346, true),
  ('GRAM-FR-EN-01', 'FR', 'GRAMMAIRE', 'Vous placez l''adjectif avant le nom comme en anglais : en français, il va généralement après.', NULL, true, 'Anglais - Adjectif', false, 347, true),
  ('GRAM-FR-EN-02', 'FR', 'GRAMMAIRE', 'Vous utilisez le present perfect anglais au lieu du passé composé français.', NULL, true, 'Anglais - Temps', false, 348, true),
  ('GRAM-FR-ES-01', 'FR', 'GRAMMAIRE', 'Vous omettez les articles comme en espagnol : ils sont obligatoires en français.', NULL, true, 'Espagnol - Articles', false, 349, true),
  ('GRAM-FR-DE-01', 'FR', 'GRAMMAIRE', 'Vous placez le verbe à la fin comme en allemand : en français, l''ordre est SVO.', NULL, true, 'Allemand - Ordre', false, 350, true),
  ('GRAM-FR-ZH-01', 'FR', 'GRAMMAIRE', 'Vous omettez les conjugaisons comme en chinois : en français, le verbe se conjugue.', NULL, true, 'Chinois - Conjugaison', false, 351, true),
  ('GRAM-FR-RU-01', 'FR', 'GRAMMAIRE', 'Vous omettez les articles comme en russe : ils sont essentiels en français.', NULL, true, 'Russe - Articles', false, 352, true),
  ('GRAM-FR-PT-01', 'FR', 'GRAMMAIRE', 'Vous confondez les structures proches du portugais : attention aux faux amis.', NULL, true, 'Portugais - Faux amis', false, 353, true),
  ('TECH-FR-V01', 'FR', 'VOCABULAIRE', 'Rappel : école de ski, cours/leçon, débutant, intermédiaire, confirmé/expert.', 'Niveaux', false, NULL, true, 354, true),
  ('TECH-FR-V02', 'FR', 'VOCABULAIRE', 'Rappel : chasse-neige, virage parallèle, bâtons, carres.', 'Technique', false, NULL, true, 355, true),
  ('TECH-FR-V03', 'FR', 'VOCABULAIRE', 'Rappel : pliez les genoux, penchez-vous en avant, transfert de poids.', 'Instructions', false, NULL, true, 356, true),
  ('TECH-FR-V04', 'FR', 'VOCABULAIRE', 'Rappel : télésiège, téléski, télécabine, téléphérique.', 'Remontées', false, NULL, true, 357, true),
  ('TECH-FR-V05', 'FR', 'VOCABULAIRE', 'Rappel : garde-corps, repose-pieds, lever, baisser.', 'Remontées', false, NULL, true, 358, true),
  ('TECH-FR-V06', 'FR', 'VOCABULAIRE', 'Rappel : regardez devant vous, suivez-moi, arrêtez-vous ici, très bien / bravo.', 'Instructions', false, NULL, true, 359, true),
  ('TECH-FR-V07', 'FR', 'VOCABULAIRE', 'Rappel : spatules, talons, fixations, chaussures de ski.', 'Équipement', false, NULL, true, 360, true),
  ('TECH-FR-V08', 'FR', 'VOCABULAIRE', 'Rappel : piste, piste verte/bleue/rouge/noire, hors-piste, bosses.', 'Pistes', false, NULL, true, 361, true),
  ('TECH-FR-V09', 'FR', 'VOCABULAIRE', 'Rappel : station de ski, domaine skiable.', 'Station', false, NULL, true, 362, true),
  ('TECH-FR-V10', 'FR', 'VOCABULAIRE', 'Rappel : Où avez-vous mal ? Pouvez-vous bouger ? Les secours arrivent.', 'Urgence', false, NULL, true, 363, true),
  ('EXPR-EN-01', 'EN', 'PRONONCIATION', 'Le "TH" anglais (θ / ð) est souvent remplacé par "Z" ou "S" par les francophones.', NULL, false, 'TH', true, 364, true),
  ('EXPR-EN-02', 'EN', 'PRONONCIATION', 'Votre "TH" est prononcé comme un "Z" ou "S" : placez la langue entre les dents.', NULL, true, 'TH', false, 365, true),
  ('EXPR-EN-03', 'EN', 'PRONONCIATION', 'Le "H" aspiré anglais est souvent omis par les francophones : "house" ≠ "ouse".', NULL, false, 'H aspiré', true, 366, true),
  ('EXPR-EN-04', 'EN', 'PRONONCIATION', 'Vous omettez le "H" aspiré : c''est important en anglais.', NULL, true, 'H aspiré', false, 367, true),
  ('EXPR-EN-05', 'EN', 'PRONONCIATION', 'La distinction entre voyelles courtes et longues est phonémique : "ship" vs "sheep".', NULL, false, 'Voyelles', true, 368, true),
  ('EXPR-EN-06', 'EN', 'PRONONCIATION', 'Vous ne faites pas la distinction entre les voyelles courtes et longues.', NULL, true, 'Voyelles', false, 369, true),
  ('EXPR-EN-07', 'EN', 'PRONONCIATION', 'Le "R" anglais (approximant) est différent du "R" français (uvulaire).', NULL, false, 'R', true, 370, true),
  ('EXPR-EN-08', 'EN', 'PRONONCIATION', 'Votre "R" français est trop marqué : l''anglais utilise un R approximant.', NULL, true, 'R', false, 371, true),
  ('EXPR-EN-09', 'EN', 'PRONONCIATION', 'L''accent tonique en anglais est variable et distinctif : "REcord" (n.) vs "reCORD" (v.).', NULL, false, 'Accent tonique', true, 372, true),
  ('EXPR-EN-10', 'EN', 'PRONONCIATION', 'L''accent tonique est souvent mal placé dans vos mots.', NULL, true, 'Accent tonique', false, 373, true),
  ('EXPR-EN-11', 'EN', 'PRONONCIATION', 'Les consonnes finales sont souvent avalées en anglais : "last" peut sonner "las''".', NULL, false, 'Consonnes finales', true, 374, true),
  ('EXPR-EN-12', 'EN', 'PRONONCIATION', 'Attention à l''intonation anglaise qui monte et descend différemment du français.', NULL, false, 'Intonation', true, 375, true),
  ('GRAM-EN-01', 'EN', 'GRAMMAIRE', 'Les articles "a/an/the" sont souvent mal utilisés par les francophones.', NULL, false, 'Articles', true, 376, true),
  ('GRAM-EN-02', 'EN', 'GRAMMAIRE', 'L''utilisation des articles est incorrecte : révisez a/an/the.', NULL, true, 'Articles', false, 377, true),
  ('GRAM-EN-03', 'EN', 'GRAMMAIRE', 'L''ordre des mots est SVO en anglais, comme en français.', NULL, false, 'Ordre SVO', true, 378, true),
  ('GRAM-EN-04', 'EN', 'GRAMMAIRE', 'L''adjectif se place AVANT le nom en anglais : "a big mountain", pas "a mountain big".', NULL, false, 'Adjectif', true, 379, true),
  ('GRAM-EN-05', 'EN', 'GRAMMAIRE', 'Vous placez l''adjectif après le nom comme en français : en anglais, il va avant.', NULL, true, 'Adjectif', false, 380, true),
  ('GRAM-EN-06', 'EN', 'GRAMMAIRE', 'Le présent simple vs présent continu : "I ski" (habitude) vs "I am skiing" (maintenant).', NULL, false, 'Present simple/continu', true, 381, true),
  ('GRAM-EN-07', 'EN', 'GRAMMAIRE', 'Vous confondez le présent simple et le présent continu.', NULL, true, 'Present simple/continu', false, 382, true),
  ('GRAM-EN-08', 'EN', 'GRAMMAIRE', 'Le present perfect exprime un lien avec le présent : "I have skied" (expérience de vie).', NULL, false, 'Present perfect', true, 383, true),
  ('GRAM-EN-09', 'EN', 'GRAMMAIRE', 'Vous utilisez mal le present perfect : il n''équivaut pas exactement au passé composé.', NULL, true, 'Present perfect', false, 384, true),
  ('GRAM-EN-10', 'EN', 'GRAMMAIRE', 'Les prépositions de lieu : "at" (point), "in" (espace fermé), "on" (surface).', NULL, false, 'Prépositions', true, 385, true),
  ('GRAM-EN-11', 'EN', 'GRAMMAIRE', 'Les prépositions sont souvent incorrectes : elles diffèrent du français.', NULL, true, 'Prépositions', false, 386, true),
  ('GRAM-EN-12', 'EN', 'GRAMMAIRE', 'Les modaux (can, must, should, will) ne prennent pas de "to" : "I can ski", pas "I can to ski".', NULL, false, 'Modaux', true, 387, true),
  ('GRAM-EN-13', 'EN', 'GRAMMAIRE', 'Vous ajoutez "to" après les modaux : c''est incorrect.', NULL, true, 'Modaux', false, 388, true),
  ('GRAM-EN-14', 'EN', 'GRAMMAIRE', 'Le génitif (''s) exprime la possession : "the student''s skis" = les skis de l''élève.', NULL, false, 'Génitif', true, 389, true),
  ('GRAM-EN-15', 'EN', 'GRAMMAIRE', 'Le conditionnel : "If + past simple, would + infinitif" : "If I had time, I would ski".', NULL, false, 'Conditionnel', true, 390, true),
  ('GRAM-EN-16', 'EN', 'GRAMMAIRE', 'La structure conditionnelle est incorrecte : révisez les "if clauses".', NULL, true, 'Conditionnel', false, 391, true),
  ('GRAM-EN-17', 'EN', 'GRAMMAIRE', '"Some" (affirmatif) vs "any" (négatif/interrogatif) : "I have some skis" / "Do you have any skis?"', NULL, false, 'Some/Any', true, 392, true),
  ('GRAM-EN-18', 'EN', 'GRAMMAIRE', 'La distinction some/any n''est pas respectée.', NULL, true, 'Some/Any', false, 393, true),
  ('GRAM-EN-19', 'EN', 'GRAMMAIRE', 'Les phrasal verbs sont nombreux : "put on" (enfiler), "take off" (enlever), "slow down" (ralentir).', NULL, false, 'Phrasal verbs', true, 394, true),
  ('GRAM-EN-20', 'EN', 'GRAMMAIRE', 'Les phrasal verbs sont mal utilisés ou évités.', NULL, true, 'Phrasal verbs', false, 395, true),
  ('GRAM-EN-21', 'EN', 'GRAMMAIRE', '"For" (durée) vs "since" (point de départ) : "for 5 years" / "since 2019".', NULL, false, 'For/Since', true, 396, true),
  ('GRAM-EN-22', 'EN', 'GRAMMAIRE', 'Vous confondez "for" et "since".', NULL, true, 'For/Since', false, 397, true),
  ('GRAM-EN-23', 'EN', 'GRAMMAIRE', 'Le passif : "The lesson is given by..." (La leçon est donnée par...).', NULL, false, 'Passif', true, 398, true),
  ('GRAM-EN-24', 'EN', 'GRAMMAIRE', 'La formation du passif est incorrecte.', NULL, true, 'Passif', false, 399, true),
  ('GRAM-EN-25', 'EN', 'GRAMMAIRE', 'Le discours indirect : "He said he would come" (Il a dit qu''il viendrait).', NULL, false, 'Discours indirect', true, 400, true),
  ('GRAM-EN-26', 'EN', 'GRAMMAIRE', 'Le discours indirect est mal formé : attention au "backshift".', NULL, true, 'Discours indirect', false, 401, true),
  ('GRAM-EN-27', 'EN', 'GRAMMAIRE', '"Make" vs "do" : "make a decision" mais "do an exercise".', NULL, false, 'Make/Do', true, 402, true),
  ('GRAM-EN-28', 'EN', 'GRAMMAIRE', 'La distinction make/do est souvent incorrecte.', NULL, true, 'Make/Do', false, 403, true),
  ('GRAM-EN-29', 'EN', 'GRAMMAIRE', 'Les questions se forment avec l''auxiliaire : "Do you ski?" / "Can you ski?"', NULL, false, 'Questions', true, 404, true),
  ('GRAM-EN-30', 'EN', 'GRAMMAIRE', 'La formation des questions est incorrecte : utilisez l''auxiliaire.', NULL, true, 'Questions', false, 405, true),
  ('GRAM-EN-31', 'EN', 'GRAMMAIRE', 'La négation : "I don''t ski" / "I can''t ski" / "I haven''t skied".', NULL, false, 'Négation', true, 406, true),
  ('GRAM-EN-32', 'EN', 'GRAMMAIRE', 'La formation de la négation est incorrecte.', NULL, true, 'Négation', false, 407, true),
  ('GRAM-EN-33', 'EN', 'GRAMMAIRE', 'Les comparatifs : "easier" / "more difficult" / "better" (irrégulier).', NULL, false, 'Comparatifs', true, 408, true),
  ('GRAM-EN-34', 'EN', 'GRAMMAIRE', 'La formation des comparatifs est incorrecte.', NULL, true, 'Comparatifs', false, 409, true),
  ('GRAM-EN-35', 'EN', 'GRAMMAIRE', 'Les superlatifs : "the easiest" / "the most difficult" / "the best".', NULL, false, 'Superlatifs', true, 410, true),
  ('GRAM-EN-36', 'EN', 'GRAMMAIRE', 'La formation des superlatifs est incorrecte.', NULL, true, 'Superlatifs', false, 411, true),
  ('GRAM-EN-37', 'EN', 'GRAMMAIRE', '"Much" / "many" : "much snow" (indénombrable) vs "many students" (dénombrable).', NULL, false, 'Much/Many', true, 412, true),
  ('GRAM-EN-38', 'EN', 'GRAMMAIRE', 'La distinction much/many n''est pas respectée.', NULL, true, 'Much/Many', false, 413, true),
  ('GRAM-EN-39', 'EN', 'GRAMMAIRE', '"Used to" exprime une habitude passée : "I used to ski every winter".', NULL, false, 'Used to', true, 414, true),
  ('GRAM-EN-40', 'EN', 'GRAMMAIRE', 'L''utilisation de "used to" est incorrecte.', NULL, true, 'Used to', false, 415, true),
  ('TECH-EN-V01', 'EN', 'VOCABULAIRE', 'Rappel : ski school (école de ski), lesson (cours), beginner (débutant), intermediate (intermédiaire), advanced (confirmé).', 'Niveaux', false, NULL, true, 416, true),
  ('TECH-EN-V02', 'EN', 'VOCABULAIRE', 'Rappel : snowplough/pizza (chasse-neige), parallel turn (virage parallèle), poles (bâtons), edges (carres).', 'Technique', false, NULL, true, 417, true),
  ('TECH-EN-V03', 'EN', 'VOCABULAIRE', 'Rappel : bend your knees (pliez les genoux), lean forward (penchez-vous en avant), weight transfer (transfert de poids).', 'Instructions', false, NULL, true, 418, true),
  ('TECH-EN-V04', 'EN', 'VOCABULAIRE', 'Rappel : chairlift (télésiège), drag lift/button lift (téléski), gondola/cable car (télécabine).', 'Remontées', false, NULL, true, 419, true),
  ('TECH-EN-V05', 'EN', 'VOCABULAIRE', 'Rappel : safety bar (garde-corps), footrest (repose-pieds), lift up/raise (lever), lower (baisser).', 'Remontées', false, NULL, true, 420, true),
  ('TECH-EN-V06', 'EN', 'VOCABULAIRE', 'Rappel : look ahead (regardez devant), follow me (suivez-moi), stop here (arrêtez-vous ici), well done (bien joué).', 'Instructions', false, NULL, true, 421, true),
  ('TECH-EN-V07', 'EN', 'VOCABULAIRE', 'Rappel : tips (spatules), tails (talons), bindings (fixations), boots (chaussures).', 'Équipement', false, NULL, true, 422, true),
  ('TECH-EN-V08', 'EN', 'VOCABULAIRE', 'Rappel : slope/piste/run (piste), green run (piste verte), off-piste (hors-piste), moguls/bumps (bosses).', 'Pistes', false, NULL, true, 423, true),
  ('TECH-EN-V09', 'EN', 'VOCABULAIRE', 'Rappel : ski resort (station de ski), ski area (domaine skiable).', 'Station', false, NULL, true, 424, true),
  ('TECH-EN-V10', 'EN', 'VOCABULAIRE', 'Rappel : Where does it hurt? (Où avez-vous mal?), Can you move? (Pouvez-vous bouger?), Help is on the way (Les secours arrivent).', 'Urgence', false, NULL, true, 425, true),
  ('TECH-EN-V11', 'EN', 'VOCABULAIRE', 'Rappel : helmet (casque), goggles (masque), gloves (gants), jacket (veste).', 'Équipement', false, NULL, true, 426, true),
  ('TECH-EN-V12', 'EN', 'VOCABULAIRE', 'Rappel : fresh snow/powder (neige fraîche), packed snow (neige damée), icy (verglacé), slushy (neige mouillée).', 'Neige', false, NULL, true, 427, true),
  ('TECH-EN-V13', 'EN', 'VOCABULAIRE', 'Rappel : turn (virage), carving (carving), sideslip (dérapage), traverse (traversée).', 'Technique', false, NULL, true, 428, true),
  ('TECH-EN-V14', 'EN', 'VOCABULAIRE', 'Rappel : inside ski/outside ski (ski intérieur/extérieur), uphill/downhill (amont/aval).', 'Position', false, NULL, true, 429, true),
  ('TECH-EN-V15', 'EN', 'VOCABULAIRE', 'Rappel : ski patrol (pisteurs), first aid (premiers secours), stretcher/sled (brancard/luge de secours).', 'Sécurité', false, NULL, true, 430, true),
  ('TECH-EN-V16', 'EN', 'VOCABULAIRE', 'Rappel : rental shop (magasin de location), ski pass/lift ticket (forfait), piste map (plan des pistes).', 'Services', false, NULL, true, 431, true),
  ('TECH-EN-V17', 'EN', 'VOCABULAIRE', 'Rappel : fall line (ligne de pente), gradient (pente), flat section (replat).', 'Terrain', false, NULL, true, 432, true),
  ('TECH-EN-V18', 'EN', 'VOCABULAIRE', 'Rappel : balance (équilibre), stance (position), posture (posture), alignment (alignement).', 'Position', false, NULL, true, 433, true),
  ('TECH-EN-V19', 'EN', 'VOCABULAIRE', 'Rappel : pressure (pression), rotation (rotation), edging (prise de carre), steering (conduite).', 'Technique avancée', false, NULL, true, 434, true),
  ('TECH-EN-V20', 'EN', 'VOCABULAIRE', 'Rappel : Watch out! (Attention!), Coming through! (Je passe!), On your left/right! (Sur votre gauche/droite!).', 'Communication piste', false, NULL, true, 435, true),
  ('TECH-EN-V21', 'EN', 'VOCABULAIRE', 'Rappel : That''s it! (C''est ça!), Keep going! (Continuez!), You''re doing great! (Vous y êtes presque!)', 'Encouragements', false, NULL, true, 436, true),
  ('TECH-EN-V22', 'EN', 'VOCABULAIRE', 'Rappel : Try again (Essayez encore), Let''s practice (Pratiquons), One more time (Une fois de plus).', 'Pédagogie', false, NULL, true, 437, true),
  ('TECH-EN-V23', 'EN', 'VOCABULAIRE', 'Rappel : closed (fermé), open (ouvert), groomed (damé), ungroomed (non damé).', 'État des pistes', false, NULL, true, 438, true),
  ('TECH-EN-V24', 'EN', 'VOCABULAIRE', 'Rappel : avalanche risk (risque d''avalanche), weather conditions (conditions météo), visibility (visibilité).', 'Sécurité', false, NULL, true, 439, true),
  ('TECH-EN-V25', 'EN', 'VOCABULAIRE', 'Rappel : meeting point (point de rendez-vous), gathering area (zone de regroupement), departure point (point de départ).', 'Organisation', false, NULL, true, 440, true),
  ('TECH-EN-V26', 'EN', 'VOCABULAIRE', 'Rappel : warm up (échauffement), cool down (récupération), stretch (étirement), rest (repos).', 'Préparation physique', false, NULL, true, 441, true),
  ('TECH-EN-V27', 'EN', 'VOCABULAIRE', 'Rappel : children''s area (zone enfants), learning area (espace débutants), terrain park (snowpark).', 'Zones', false, NULL, true, 442, true),
  ('TECH-EN-V28', 'EN', 'VOCABULAIRE', 'Rappel : private lesson (cours particulier), group lesson (cours collectif), intensive course (stage intensif).', 'Types de cours', false, NULL, true, 443, true),
  ('TECH-EN-V29', 'EN', 'VOCABULAIRE', 'Rappel : morning session (séance du matin), afternoon session (séance de l''après-midi), full day (journée complète).', 'Horaires', false, NULL, true, 444, true),
  ('TECH-EN-V30', 'EN', 'VOCABULAIRE', 'Rappel : booking (réservation), cancellation (annulation), confirmation (confirmation), availability (disponibilité).', 'Administration', false, NULL, true, 445, true)
ON CONFLICT (code) DO UPDATE SET
  language = EXCLUDED.language,
  category = EXCLUDED.category,
  text_fr = EXCLUDED.text_fr,
  context = EXCLUDED.context,
  is_correction = EXCLUDED.is_correction,
  error_type = EXCLUDED.error_type,
  is_positive = EXCLUDED.is_positive,
  order_index = EXCLUDED.order_index,
  updated_at = now();

-- Rapport d'import journalisé : total, comptage par langue et par catégorie.
INSERT INTO public.audit_log (action, table_name, new_values)
SELECT
  'import_test_phrases',
  'test_phrases',
  jsonb_build_object(
    'migration', '20260915081000_test_phrases_seed_complete',
    'point', '7',
    'source', 'test_phrases_complete.json',
    'metadata_total_phrases', 540,
    'file_phrases', 445,
    'rows_total', (SELECT count(*) FROM public.test_phrases),
    'by_language', (
      SELECT coalesce(jsonb_object_agg(language, n), '{}'::jsonb)
      FROM (SELECT language, count(*) AS n FROM public.test_phrases GROUP BY language) s
    ),
    'by_category', (
      SELECT coalesce(jsonb_object_agg(category, n), '{}'::jsonb)
      FROM (SELECT category, count(*) AS n FROM public.test_phrases GROUP BY category) s
    ),
    'corrections', (SELECT count(*) FROM public.test_phrases WHERE is_correction),
    'explanations', (SELECT count(*) FROM public.test_phrases WHERE NOT is_correction),
    'with_context', (SELECT count(*) FROM public.test_phrases WHERE context IS NOT NULL),
    'with_error_type', (SELECT count(*) FROM public.test_phrases WHERE error_type IS NOT NULL)
  );
